### ISSUE TITLE
Few Questions regarding the Code

### ISSUE THREAD

**Issue by taxsmartindia** [foundry/OpenCVStitch#1]
Hi, 

First of all, thank you for writing such a useful code. I had searched all the internet for stitching code and finally found the one which works.

However, I have few questions for you:

1) It takes alot of time to stitch images. Approx 2 minute for 5-6 images and around 6 min for 10 images. Is there a way I can speed up the process?

2) Sometimes all images get stitched in simulator but in device only few of them get stitched. What could be the issue?

3) Edges of final panorama are not smooth. How can I make it smooth?

4) From where can I set the  percentage of image content to be overlapped? Currently it seems it overlaps around 30% of the image. I want to reduce this so that I can get Panorama by taking just 15 images.

If you can spare sometime and guide me on this, I would be really grateful to you.

Thank you.

Priyadarshan Joshi

**Comment by foundry** [comment]
Hello Priyadarshan

I am glad that you have found this code sample useful. As you have noticed, it is actually a very basic or high-level example of stitching, and there are a huge number of ways you can optimise.

I am afraid I am too busy to look at this in detail, other than to point you towards the code and documentation.

In my sample, the two important lines are these:

```
  Stitcher stitcher = Stitcher::createDefault(try_use_gpu);
  Stitcher::Status status = stitcher.stitch(imgs, pano);
```

we have already set `try_use_gpu = false`; you can set it to true, see if that makes a difference (it may not).

You might also notice [from the docs](http://docs.opencv.org/modules/stitching/doc/high_level.html#stitcher-stitch) that there is a second form of `Stitcher::stitch`:  

```
 Status Stitcher::stitch(InputArray images, 
                                    const std::vector<std::vector<Rect>>& rois, 
                                    OutputArray pano)
```

Where `rois` = Region of interest rectangles.

This _might_ enable you to take control of the overlap (by supplying rects for the overlapping regions), and at the same time could speed up the processs. In general, the more information you can supply to the process, the more efficient the algorithms can be. 

Otherwise you are going to have to take a deep dive into the science of stitching. Here is the [openCV stitching documentation](http://docs.opencv.org/modules/stitching/doc/stitching.html).

You will want to start with [higher-level functionality](http://docs.opencv.org/modules/stitching/doc/high_level.html#), and then you will need to look at the [stitching pipeline](http://docs.opencv.org/modules/stitching/doc/introduction.html#stitching-pipeline) and it's associated background reading. 

Then it depends on how much time you want to spend getting to know the stitching process. There are a [huge number of classes](http://docs.opencv.org/modules/stitching/doc/stitching.html) that you can take advantage of to intervene in the process.

I am sorry I cannot be more directly helpful. If you manage to come up with further optimisations, I would be glad to hear about them, it would encourage me to update this code sample.

Best wishes!

foundry
